import React, { createContext, useContext, useEffect, useMemo, useState } from 'react';

type SupportedLanguageCode = 'en' | 'war' | 'tl';

type TranslationDictionary = Record<string, string>;

type TranslationsBundle = Record<SupportedLanguageCode, TranslationDictionary>;

const LANGUAGE_STORAGE_KEY = 'app_language_code';

const defaultTranslations: TranslationsBundle = {
  en: {
    app_name: 'MarkIt',
    settings: 'Settings',
    general: 'General',
    leave_feedback: 'Leave feedback',
    leave_feedback_sub: 'Let us know how you like the app!'
    ,
    clear_cache: 'Clear cache',
    help_support: 'Help & Support',
    legal: 'Legal',
    privacy_policy: 'Privacy Policy',
    terms_of_service: 'Terms of Service',
    sign_out: 'Sign out',
    danger: 'DANGER',
    delete_account: 'Delete Account',
    cancel: 'Cancel',
    send: 'Send',
    sending: 'Sending...',
    language: 'Language',
    language_english: 'English',
    language_waray: 'Waray',
    // Navigation and menus
    nav_home: 'Home',
    nav_search: 'Search',
    nav_create: 'Create',
    nav_messages: 'Messages',
    nav_notifications: 'Notifications',
    nav_profile: 'Profile',
    nav_mydashboard: 'My Dashboard',
    nav_farmers: 'Farmers',
    nav_admin: 'Admin',
    bottom_nav: 'Bottom navigation',
    menu: 'Menu',
    menu_farmers_directory: 'Farmers Directory',
    menu_price_guarantee: 'Price Guarantee',
    menu_help: 'Help',
    account: 'Account',
    view_profile: 'View Profile',
    // Roles
    role_farmer: 'Farmer',
    role_fisherman: 'Fisherman',
    role_buyer: 'Buyer',
    role_admin: 'Admin',
    role_user: 'User',
    // Home/Dashboard/MyDashboard/Create
    welcome_title: 'Welcome to MarkIt',
    welcome_farmer: 'Connect directly with buyers and get fair prices for your harvest',
    welcome_fisherman: 'Connect directly with buyers and get fair prices for your catch',
    welcome_buyer: 'Discover fresh harvests from local farmers and fisherfolk',
    welcome_admin: 'Monitor platform activity and user management',
    location_not_set: 'Location not set',
    home_all_harvests: 'All Harvests',
    home_new_harvest: 'New Harvest',
    home_all_harvests_desc: 'Browse all harvests from you and other farmers',
    home_all_harvests_buyer_desc: 'Browse all harvests from farmers and fisherfolk',
    by: 'by',
    you: 'You',
    your_post: 'Your Post',
    view_details: 'View Details',
    edit: 'Edit',
    purchase: 'Purchase',
    quantity: 'Quantity',
    base_price: 'Base Price',
    location: 'Location',
    search_ph: 'Search products, farmers, locations...',
    mydashboard_title: 'My Dashboard',
    // Create page keys
    create_post_title: 'Post New Harvest',
    create_post_subtitle: 'Share your harvest with buyers and get fair prices through our bidding system',
    create_basic_info: 'Basic Information',
    create_basic_info_desc: 'Tell buyers about your harvest',
    create_title_label: 'Harvest Title *',
    create_title_ph: 'e.g., Fresh Organic Tomatoes',
    create_category_label: 'Category *',
    create_category_ph: 'Select category',
    create_subcategory_label: 'Subcategory *',
    create_subcategory_ph: 'Select subcategory',
    create_description_label: 'Description *',
    create_description_ph: 'Describe your harvest, growing methods, quality, etc.',
    create_media: 'Photos & Videos',
    create_media_desc: 'Upload photos and videos of your harvest (max 10 files, 10MB each)',
    uploading: 'Uploading...',
    upload_hint: 'Click to upload or drag and drop',
    upload_types_hint: 'PNG, JPG, MP4, MOV up to 10MB each',
    create_quantity_quality: 'Quantity & Quality',
    create_quantity_quality_desc: 'Specify the amount and quality of your harvest',
    create_quantity_label: 'Quantity *',
    unit: 'Unit',
    create_base_price: 'Base Price (₱ per unit) *',
    create_quality_grade: 'Quality Grade',
    grade_premium: 'Premium',
    grade_a: 'Grade A',
    grade_b: 'Grade B',
    grade_c: 'Grade C',
    create_freshness: 'Freshness',
    fresh: 'Fresh',
    frozen: 'Frozen',
    dried: 'Dried',
    processed: 'Processed',
    create_certifications: 'Certifications',
    create_organic: 'Organic/All-natural',
    create_dates: 'Important Dates',
    create_dates_desc: 'Set harvest and expiry dates',
    create_harvest_date: 'Harvest Date',
    pick_date: 'Pick a date',
    create_expiry_date: 'Expiry Date (Optional)',
    create_location: 'Location',
    create_location_desc: 'Where is your harvest located?',
    create_location_label: 'Harvest Location *',
    create_location_ph: 'Enter your farm or harvest location (e.g., Barangay San Jose, Nueva Ecija)',
    create_location_hint: 'Be specific about your location to help buyers find you',
    create_delivery: 'Delivery Options',
    create_delivery_desc: 'How can buyers receive your harvest?',
    create_allow_pickup: 'Allow pickup from your location',
    create_offer_delivery: 'Offer delivery service',
    create_delivery_radius: 'Delivery Radius (km)',
    create_delivery_fee: 'Delivery Fee (₱)',
    posting: 'Posting...',
    post_harvest: 'Post Harvest',
    // Messages/Search
    messages_title: 'Messages',
    messages_new_chat: 'New Chat',
    messages_search_ph: 'Search conversations...',
    messages_empty_title: 'No conversations yet',
    messages_empty_desc: 'Start a conversation with farmers or buyers about their harvests',
    messages_start_chat: 'Start New Chat',
    back: 'Back',
    online: 'Online',
    messages_none: 'No messages yet. Start a conversation!',
    messages_input_ph: 'Type a message...',
    messages_welcome: 'Welcome to Messages',
    messages_welcome_desc: 'Start conversations with farmers and buyers about harvests',
    messages_tip_contact: 'Contact farmers about their products',
    messages_tip_negotiate: 'Negotiate prices and delivery',
    messages_tip_quality: 'Ask questions about harvest quality',
    just_now: 'Just now',
    search: 'Search',
    search_users: 'Search Users',
    search_input_ph: 'Search by name, email, or LRN...',
    filter: 'Filter',
    all: 'All',
    students: 'Students',
    teachers: 'Teachers',
    search_results: 'Search Results',
    view_full_profile: 'View Full Profile',
    message: 'Message',
    no_results: 'No results found',
    try_different_keywords: 'Try searching with different keywords.',
  },
  war: {
    app_name: 'MarkIt',
    settings: 'Mga Setting',
    general: 'Generál',
    leave_feedback: 'Pagbilin hin feedback',
    leave_feedback_sub: 'Siringa kami kun ano an imo hunahuna han app!'
    ,
    clear_cache: 'Limpyohi an cache',
    help_support: 'Bulig & Suporta',
    legal: 'Legal',
    privacy_policy: 'Polisiya ha Pagkapriba',
    terms_of_service: 'Mga Termino han Serbisyo',
    sign_out: 'Pag-log out',
    danger: 'DELÍKADO',
    delete_account: 'Paraon an Akun',
    cancel: 'Kanselahon',
    send: 'Ipadara',
    sending: 'Nagpapadara...',
    language: 'Yinaknan',
    language_english: 'Ininglis',
    language_waray: 'Waray',
    // Navigation and menus
    nav_home: 'Balay',
    nav_search: 'Pangita',
    nav_create: 'Paghimo',
    nav_messages: 'Mensahe',
    nav_notifications: 'Notipikasyon',
    nav_profile: 'Profil',
    nav_mydashboard: 'Akong Dashboard',
    nav_farmers: 'Mag-uuma',
    nav_admin: 'Admin',
    bottom_nav: 'Igbaw nga nabigasyon',
    menu: 'Menu',
    menu_farmers_directory: 'Direktoryo han mga Parag-uma',
    menu_price_guarantee: 'Garantisado nga Presyo',
    menu_help: 'Bulig',
    account: 'Asaynta',
    view_profile: 'Kitaa an Profil',
    // Roles
    role_farmer: 'Parag-uma',
    role_fisherman: 'Mangingisda',
    role_buyer: 'Parapalit',
    role_admin: 'Admin',
    role_user: 'Gumaramit',
    // Home/Dashboard/MyDashboard/Create
    welcome_title: 'Welcome ha MarkIt',
    welcome_farmer: 'Direkta pagkonektar ha mga parapalit para ha husto nga presyo han imo ani',
    welcome_fisherman: 'Direkta pagkonektar ha mga parapalit para ha husto nga presyo han imo kuha',
    welcome_buyer: 'Diskubrihi an presko nga ani tikang ha mga lokal nga parag-uma ug mangingisda',
    welcome_admin: 'Bantayi an kalihokan han plataporma ngan pagdumara han mga gumagamit',
    location_not_set: 'Waray setting ha lokasyon',
    home_all_harvests: 'Ngatanan nga Ani',
    home_new_harvest: 'Bag-o nga Ani',
    home_all_harvests_desc: 'Kitaa an ngatanan nga ani tikang ha imo ngan iba nga parag-uma',
    home_all_harvests_buyer_desc: 'Kitaa an ngatanan nga ani tikang ha mga parag-uma ug mangingisda',
    by: 'ni',
    you: 'Ikaw',
    your_post: 'Imo Post',
    view_details: 'Kitaa an Detalye',
    edit: 'Usba',
    purchase: 'Palita',
    quantity: 'Kantidad',
    base_price: 'Base nga Presyo',
    location: 'Lokasyon',
    search_ph: 'Pangitaa an produkto, parag-uma, lokasyon...',
    mydashboard_title: 'Akong Dashboard',
    // Create page keys
    create_post_title: 'I-post an Bag-o nga Ani',
    create_post_subtitle: 'Ibahin an imo ani ha mga parapalit para ha husto nga presyo pinaagi han among bidding',
    create_basic_info: 'Panguna nga Impormasyon',
    create_basic_info_desc: 'Siringi an mga parapalit mahitungod han imo ani',
    create_title_label: 'Titulo han Ani *',
    create_title_ph: 'pananglitan: Presko nga Organiko nga Kamatis',
    create_category_label: 'Kategorya *',
    create_category_ph: 'Pumili hin kategorya',
    create_subcategory_label: 'Sub-kategorya *',
    create_subcategory_ph: 'Pumili hin sub-kategorya',
    create_description_label: 'Deskripsyon *',
    create_description_ph: 'Isaysay an imo ani, pamaagi ha pagtano, kalidad, ug iba pa.',
    create_media: 'Mga Litrato & Bidyo',
    create_media_desc: 'I-upload an mga litrato ug bidyo han imo ani (max 10 files, 10MB tagsa)',
    uploading: 'Nag-i-upload...',
    upload_hint: 'Pinduta basi mag-upload o idrag ug ibutang dinhi',
    upload_types_hint: 'PNG, JPG, MP4, MOV tubtob 10MB tagsa',
    create_quantity_quality: 'Kantidad & Kalidad',
    create_quantity_quality_desc: 'Ibutang an kadamo ug kalidad han imo ani',
    create_quantity_label: 'Kantidad *',
    unit: 'Yunit',
    create_base_price: 'Base nga Presyo (₱ kada yunit) *',
    create_quality_grade: 'Grado han Kalidad',
    grade_premium: 'Premium',
    grade_a: 'Grado A',
    grade_b: 'Grado B',
    grade_c: 'Grado C',
    create_freshness: 'Kapreskohan',
    fresh: 'Presko',
    frozen: 'Ginpaligon',
    dried: 'Tuyo',
    processed: 'Prinoseso',
    create_certifications: 'Mga Sertipikasyon',
    create_organic: 'Organiko/Natural la',
    create_dates: 'Mahinungdanon nga Petsa',
    create_dates_desc: 'I-set an petsa han pag-ani ug expiry',
    create_harvest_date: 'Petsa han Ani',
    pick_date: 'Pumili hin petsa',
    create_expiry_date: 'Expiry Date (Opsyonal)',
    create_location: 'Lokasyon',
    create_location_desc: 'Hain nahimumutang an imo ani?',
    create_location_label: 'Lokasyon han Ani *',
    create_location_ph: 'Ibutang an lokasyon han imo uma o ani (pananglitan, Brgy. San Jose, Nueva Ecija)',
    create_location_hint: 'Paklaroha an lokasyon basi sayon ka makita han mga parapalit',
    create_delivery: 'Mga Opsyon ha Paghatud',
    create_delivery_desc: 'Paonan-o makakakarawat an parapalit han imo ani?',
    create_allow_pickup: 'Tugoti an pag-pickup ha imo lokasyon',
    create_offer_delivery: 'Mag-alok hin serbisyo ha paghatud',
    create_delivery_radius: 'Radius han Paghatud (km)',
    create_delivery_fee: 'Bayad ha Paghatud (₱)',
    posting: 'Ginpo-post...',
    post_harvest: 'I-post an Ani',
    // Messages/Search
    messages_title: 'Mga Mensahe',
    messages_new_chat: 'Bag-o nga Chat',
    messages_search_ph: 'Pangitaa an mga pakighimangraw...',
    messages_empty_title: 'Waray pa mga panhisayod',
    messages_empty_desc: 'Sugdi an pakighimangraw ha mga parag-uma o parapalit mahitungod han ira ani',
    messages_start_chat: 'Sugdi an Bag-o nga Chat',
    back: 'Balik',
    online: 'Online',
    messages_none: 'Waray pa mensahe. Sugdi an pakighimangraw!',
    messages_input_ph: 'Sumat hin mensahe...',
    messages_welcome: 'Welcome ha Mensahe',
    messages_welcome_desc: 'Sugdi an pakighimangraw ha mga parag-uma ug parapalit',
    messages_tip_contact: 'Pakig-istorya ha mga parag-uma parti han ira produkto',
    messages_tip_negotiate: 'Pagbalyuanay han presyo ug paghatud',
    messages_tip_quality: 'Pangutana parti han kalidad han ani',
    just_now: 'Kakadi la',
    search: 'Pangita',
    search_users: 'Pangita hin Gumaramit',
    search_input_ph: 'Pangita pinaagi han ngaran, email, o LRN...',
    filter: 'Pagsala',
    all: 'Ngatanan',
    students: 'Mga Estudyante',
    teachers: 'Mga Magturutdo',
    search_results: 'Mga Resulta han Pangita',
    view_full_profile: 'Kitaa an Bug-os nga Profile',
    message: 'Mensahe',
    no_results: 'Waray nakuha nga resulta',
    try_different_keywords: 'Sulayi an lain nga mga pulong.',
  },
  tl: {
    app_name: 'MarkIt',
    settings: 'Mga Setting',
    general: 'Pangkalahatan',
    leave_feedback: 'Mag-iwan ng puna',
    leave_feedback_sub: 'Sabihin sa amin kung ano ang tingin mo sa app!'
    ,
    clear_cache: 'I-clear ang cache',
    help_support: 'Tulong at Suporta',
    legal: 'Legal',
    privacy_policy: 'Patakaran sa Privacy',
    terms_of_service: 'Mga Tuntunin ng Serbisyo',
    sign_out: 'Mag-log out',
    danger: 'BABALA',
    delete_account: 'Burahin ang Account',
    cancel: 'Kanselahin',
    send: 'Ipadala',
    sending: 'Nagpapadala...',
    language: 'Wika',
    language_english: 'Ingles',
    language_waray: 'Waray',
    // Navigation and menus
    nav_home: 'Home',
    nav_search: 'Hanapin',
    nav_create: 'Lumikha',
    nav_messages: 'Mensahes',
    nav_notifications: 'Abiso',
    nav_profile: 'Profile',
    nav_mydashboard: 'Aking Dashboard',
    nav_farmers: 'Magsasaka',
    nav_admin: 'Admin',
    bottom_nav: 'Bottom navigation',
    menu: 'Menu',
    menu_farmers_directory: 'Direktoryo ng mga Magsasaka',
    menu_price_guarantee: 'Garantisadong Presyo',
    menu_help: 'Tulong',
    account: 'Account',
    view_profile: 'Tingnan ang Profile',
    // Roles
    role_farmer: 'Magsasaka',
    role_fisherman: 'Mangingisda',
    role_buyer: 'Mamimili',
    role_admin: 'Admin',
    role_user: 'Gumagamit',
    // Home/Dashboard/MyDashboard/Create
    welcome_title: 'Maligayang pagdating sa MarkIt',
    welcome_farmer: 'Kumonekta direkta sa mga mamimili at makakuha ng patas na presyo sa ani',
    welcome_fisherman: 'Kumonekta direkta sa mga mamimili at makakuha ng patas na presyo sa huli',
    welcome_buyer: 'Tuklasin ang mga sariwang ani mula sa lokal na magsasaka at mangingisda',
    welcome_admin: 'Subaybayan ang aktibidad ng plataporma at pamamahala ng user',
    location_not_set: 'Walang lokasyon',
    home_all_harvests: 'Lahat ng Ani',
    home_new_harvest: 'Bagong Ani',
    home_all_harvests_desc: 'Tingnan ang lahat ng ani mula sa iyo at ibang magsasaka',
    home_all_harvests_buyer_desc: 'Tingnan ang lahat ng ani mula sa mga magsasaka at mangingisda',
    by: 'ni',
    you: 'Ikaw',
    your_post: 'Iyong Post',
    view_details: 'Tingnan ang Detalye',
    edit: 'I-edit',
    purchase: 'Bumili',
    quantity: 'Dami',
    base_price: 'Batayang Presyo',
    location: 'Lokasyon',
    search_ph: 'Maghanap ng produkto, magsasaka, lokasyon...',
    mydashboard_title: 'Aking Dashboard',
    // Create page keys
    create_post_title: 'Mag-post ng Bagong Ani',
    create_post_subtitle: 'Ibahagi ang ani sa mga mamimili at magkaroon ng patas na presyo sa bidding',
    create_basic_info: 'Pangunahing Impormasyon',
    create_basic_info_desc: 'Ilarawan sa mamimili ang tungkol sa iyong ani',
    create_title_label: 'Pamagat ng Ani *',
    create_title_ph: 'hal., Sariwang Organikong Kamatis',
    create_category_label: 'Kategorya *',
    create_category_ph: 'Pumili ng kategorya',
    create_subcategory_label: 'Subkategorya *',
    create_subcategory_ph: 'Pumili ng subkategorya',
    create_description_label: 'Paglalarawan *',
    create_description_ph: 'Ilarawan ang ani, paraan ng pagtatanim, kalidad, atbp.',
    create_media: 'Mga Larawan at Bidyo',
    create_media_desc: 'Mag-upload ng mga larawan at bidyo ng ani (max 10 files, 10MB bawat isa)',
    uploading: 'Nag-a-upload...',
    upload_hint: 'I-click para mag-upload o i-drag at i-drop',
    upload_types_hint: 'PNG, JPG, MP4, MOV hanggang 10MB bawat isa',
    create_quantity_quality: 'Dami at Kalidad',
    create_quantity_quality_desc: 'Ilagay ang dami at kalidad ng iyong ani',
    create_quantity_label: 'Dami *',
    unit: 'Yunit',
    create_base_price: 'Batayang Presyo (₱ bawat yunit) *',
    create_quality_grade: 'Antas ng Kalidad',
    grade_premium: 'Premium',
    grade_a: 'Antas A',
    grade_b: 'Antas B',
    grade_c: 'Antas C',
    create_freshness: 'Kasariwaan',
    fresh: 'Sariwa',
    frozen: 'Frozen',
    dried: 'Tuyo',
    processed: 'Prinoseso',
    create_certifications: 'Mga Sertipikasyon',
    create_organic: 'Organiko/Likas',
    create_dates: 'Mahalagang Petsa',
    create_dates_desc: 'Itakda ang petsa ng ani at pag-expire',
    create_harvest_date: 'Petsa ng Ani',
    pick_date: 'Pumili ng petsa',
    create_expiry_date: 'Petsa ng Pag-expire (Opsyonal)',
    create_location: 'Lokasyon',
    create_location_desc: 'Saan matatagpuan ang iyong ani?',
    create_location_label: 'Lokasyon ng Ani *',
    create_location_ph: 'Ilagay ang lokasyon (hal., Brgy. San Jose, Nueva Ecija)',
    create_location_hint: 'Maging tiyak para madaling mahanap ng mamimili',
    create_delivery: 'Mga Opsyon sa Paghahatid',
    create_delivery_desc: 'Paano matatanggap ng mamimili ang iyong ani?',
    create_allow_pickup: 'Payagan ang pickup sa iyong lokasyon',
    create_offer_delivery: 'Mag-alok ng serbisyo sa paghahatid',
    create_delivery_radius: 'Saklaw ng Paghahatid (km)',
    create_delivery_fee: 'Bayad sa Paghahatid (₱)',
    posting: 'Nagpo-post...',
    post_harvest: 'I-post ang Ani',
    // Messages/Search
    messages_title: 'Mga Mensahe',
    messages_new_chat: 'Bagong Chat',
    messages_search_ph: 'Maghanap ng mga usapan...',
    messages_empty_title: 'Wala pang usapan',
    messages_empty_desc: 'Magsimula ng usapan sa magsasaka o mamimili tungkol sa ani',
    messages_start_chat: 'Magsimula ng Chat',
    back: 'Bumalik',
    online: 'Online',
    messages_none: 'Wala pang mensahe. Magsimula ng usapan!',
    messages_input_ph: 'Mag-type ng mensahe...',
    messages_welcome: 'Maligayang pagdating sa Mensahe',
    messages_welcome_desc: 'Magsimula ng usapan sa magsasaka at mamimili tungkol sa ani',
    messages_tip_contact: 'Makipag-ugnayan sa magsasaka tungkol sa kanilang produkto',
    messages_tip_negotiate: 'Makipagtawaran sa presyo at delivery',
    messages_tip_quality: 'Magtanong tungkol sa kalidad ng ani',
    just_now: 'Kaninang-kanina lang',
    search: 'Hanapin',
    search_users: 'Maghanap ng User',
    search_input_ph: 'Maghanap ayon sa pangalan, email, o LRN...',
    filter: 'Salain',
    all: 'Lahat',
    students: 'Mga Estudyante',
    teachers: 'Mga Guro',
    search_results: 'Mga Resulta ng Paghahanap',
    view_full_profile: 'Tingnan ang Buong Profile',
    message: 'Mensahe',
    no_results: 'Walang nakitang resulta',
    try_different_keywords: 'Subukang maghanap gamit ang ibang salita.',
  },
};

interface LanguageContextValue {
  language: SupportedLanguageCode;
  setLanguage: (code: SupportedLanguageCode) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextValue | undefined>(undefined);

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be used within LanguageProvider');
  return ctx;
}

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<SupportedLanguageCode>('en');

  useEffect(() => {
    const stored = localStorage.getItem(LANGUAGE_STORAGE_KEY) as SupportedLanguageCode | null;
    if (stored === 'en' || stored === 'war') {
      setLanguageState(stored);
    }
  }, []);

  const setLanguage = (code: SupportedLanguageCode) => {
    setLanguageState(code);
    localStorage.setItem(LANGUAGE_STORAGE_KEY, code);
  };

  const t = useMemo(() => {
    return (key: string) => {
      const dict = defaultTranslations[language] || defaultTranslations.en;
      return dict[key] ?? defaultTranslations.en[key] ?? key;
    };
  }, [language]);

  const value: LanguageContextValue = {
    language,
    setLanguage,
    t,
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
}

export type { SupportedLanguageCode };
export const translations = defaultTranslations;



